[tool.mypy]
python_version = 3.10
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "requests"
ignore_missing_imports = true

[tool.black]
target-version = ['py310']
include = '\.py$'
line-length = 120

[tool.isort]
profile = "black"
py_version = 310
line_length = 120
